# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5f289be38d32e240d24189f36f5e1822c6a46251fa95455895f548829094cc66a22306606daa819cb685b738d0e1a74b7dee151b82c6873ad883bb545b01462

test:
  secret_key_base: 162d0d86dacd45329f6aec402cff02f67269e6495ea4c36edadd0ec945192609ec2d3c1e3b0ff1d69ee3e9e0c23ab78a99ef28fe86ced71bcbd78d95cc769e41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
